#:kivy 2.2.1

<StatsContinentScreen>:

    RelativeLayout:
        pos_hint: {"center_x": 0.5, "y": 0.025}
        size_hint: (0.9, 0.775 - 0.015 - 0.025*2)

        CustomScrollview:
            id: scrollview
            bar_width: 0
            size_hint: (1, 1)

            MyScrollViewLayout:
                id: scrollview_layout
                cols: 1
                spacing: 10*root.font_ratio
                padding: 10*root.font_ratio
